#!/usr/bin/env node
/**
 * Embed skills/flowscan/SKILL.md (the single source of truth for tool-selection
 * guidance) into src/guide.ts, so the server can serve it as the MCP prompt
 * `flowscan_guide` and the resource `flowscan://guide` to clients that cannot
 * load Claude skills.
 *
 *   node scripts/gen-guide.mjs          # (re)generate src/guide.ts   (npm run guide)
 *   node scripts/gen-guide.mjs --check  # exit 1 if src/guide.ts is stale (run by npm run build)
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = "skills/flowscan/SKILL.md";
const OUT = "src/guide.ts";

const raw = readFileSync(path.join(ROOT, SRC), "utf8").replace(/\r\n/g, "\n");
const fm = raw.match(/^---\n([\s\S]*?)\n---\n/);
const body = (fm ? raw.slice(fm[0].length) : raw).trim() + "\n";
const description = fm?.[1].match(/^description:\s*(.+)$/m)?.[1].trim() ?? "";
const sha = createHash("sha256").update(raw).digest("hex");

const ts = `// GENERATED by scripts/gen-guide.mjs from ${SRC}. Do not edit by hand: run \`npm run guide\`.
// \`npm run build\` fails if this file is out of date with ${SRC}.
export const GUIDE_SOURCE = ${JSON.stringify(SRC)};
export const GUIDE_SHA256 = ${JSON.stringify(sha)};
/** The skill's frontmatter description: when to use the Flowscan tools. */
export const GUIDE_DESCRIPTION = ${JSON.stringify(description)};
/** SKILL.md without its YAML frontmatter. */
export const GUIDE_MD = ${JSON.stringify(body)};
`;

if (process.argv.includes("--check")) {
  const current = existsSync(path.join(ROOT, OUT)) ? readFileSync(path.join(ROOT, OUT), "utf8") : "";
  if (current !== ts) {
    process.stderr.write(`${OUT} is out of date with ${SRC}. Run \`npm run guide\` and commit the result.\n`);
    process.exit(1);
  }
} else {
  writeFileSync(path.join(ROOT, OUT), ts);
  process.stderr.write(`wrote ${OUT} (${body.length} chars, sha256 ${sha.slice(0, 12)})\n`);
}
